# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-20 06:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(null=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(default=datetime.date(2017, 5, 20), verbose_name='Дата загрузки')),
            ],
        ),
    ]
