# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-20 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20170520_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='slug',
        ),
    ]
